### ISSUE TITLE
Add freeform block elements for use on homepage (Image, links)

### ISSUE THREAD

**Issue by brandonhundt** [PublicRadioInternational/pri-component-library#113]
See PRI.org #888. Ensure image and link styling render like episode cards do *if* its used on the homepage. 

Lists in the body do not respect styling.

**Comment by brandonhundt** [comment]
Contextual steps.

1. Create a new freeform block
2. Add in content to all the fields including the links field. and save.
3. Edit the Homepage.
4. Add a new card containing the freeform block.
5. Note how fields are missing that are displayed on the Drupal side.

**Comment by rpeterman-gp** [comment]
Need to create a new homepage card type that only has an entity reference field for a freeform block. Freeform data basically duplicates and extends homepage cards, so can handle all the data to display.
